Controllers films users
gray-alt/java-filmorate pull request #3
Opened 2023-04-07 08:47 UTC by gray-alt

Добавлены контроллеры фильмов и пользователей.

2023-04-07 16:48 UTC, EugeneLenkevich requested changes
Привет, Сергей, спасибо за PR

В целом все отлично :)
Есть совсем небольшие пометки, посмотри комментарии ниже, пожалуйста

2023-04-07 16:48 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/FilmController.java
> +    private final HashMap<Integer, Film> films = new HashMap<>();
Давай ка все таки вот так сделаем, с интерфейсом

private final Map<Integer, Film> films = new HashMap<>();

PS
Вообще, можно использовать ConcurrentHashMap. Web - конкурентная среда :)

https://habr.com/ru/post/132884/

2023-04-07 16:48 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/UserController.java
> +        if (userName == null || userName.isBlank()) {
Для проверки строк на пустоту можно использовать 
StringUtils.hasText
или же аналогичную функцию из apache commons 
StringUtils.isNotBlank
=)

2023-04-07 16:48 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/exception/ValidationException.java
> +    public synchronized Throwable fillInStackTrace() {
А зачем тут synchronized, тут всего одна операция, да и то которая ничего не изменяет :)
Раз уж ресь зашла, логично было бы сделать синхронизованным увеличение счетчика lastId, на случай если две операции начали его увеличивать одновременно

2023-04-10 07:21 UTC, gray-alt commented
Привет. 
Внёс изменения в код. А synchronized IDEA поставила сама, а я не обратил внимания в своё время.

2023-04-10 07:53 UTC, EugeneLenkevich approved these changes
Теперь все отлично, спасибо :)

PS
ну, зато, идея подкинула повод обратить внимание на synchronized :)

2023-04-10 08:51 UTC, merged