Add database
gray-alt/java-filmorate pull request #5
Opened 2023-05-25 16:53 UTC by gray-alt

2023-05-25 18:48 UTC, EugeneLenkevich requested changes
Привет, Сергей, спасибо за PR

В целом все отлично :)
SQL-запросы супер, но пару моментиков отметил

2023-05-25 18:48 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/controller/OtherController.java
> +public class OtherController {
А почему OtherController, можно же для каждой сущности отдельный сделать. А то получается некоторая свалка всего :)

2023-05-25 18:48 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/FilmDbStorage.java
> +        return Optional.of(genres.get(0));
Optional.of(genres.get(0));

вот так вроде то же самое :)
 
return genres.findFirst();

2023-05-25 18:48 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +                .sorted((f0, f1) -> f1.getLikes().size() - f0.getLikes().size())
А не лучше ли сортировку делать на стороне СУБД, она это гораздо эффективнее делает

.limit(count)
а вот это точно лучше на стороне БД дедлать, так у нас в итоге память может кончиться :)

2023-05-26 06:41 UTC, gray-alt commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +                .sorted((f0, f1) -> f1.getLikes().size() - f0.getLikes().size())
Так это класс хранения данных в памяти с прошлого спринта ))

2023-05-26 12:39 UTC, EugeneLenkevich commented on src/main/java/ru/yandex/practicum/filmorate/storage/film/InMemoryFilmStorage.java
> +                .sorted((f0, f1) -> f1.getLikes().size() - f0.getLikes().size())
ну ок :)

2023-05-26 12:40 UTC, EugeneLenkevich approved these changes
Теперь все отлично, спасибо :)

2023-05-30 09:04 UTC, merged